// ==========================================================
// SplitPay sample data seed script
//
// Usage:
//   mongosh "mongodb://localhost:27017/splitpay" sample-data/seed.js
//
// Notes:
// - Passwords below are BCrypt hashes of "password123" (cost factor 10),
//   so every seeded user can log in with email + "password123".
// - This script is idempotent-ish: it drops and recreates the collections
//   it touches, so re-running it gives you a clean, consistent dataset.
// - IDs are fixed strings so you can paste them straight into Postman
//   variables or the frontend without hunting through query results.
// ==========================================================

const bcryptHashOfPassword123 = "$2a$10$DowQF8xXwHVfV2Yl3s6EOO0m2yV1s7q1Kq2b8n5r6t2r0jz1a2b3c";
// NOTE: replace the hash above with a real BCrypt hash generated by the
// backend (e.g. via a throwaway /api/auth/register call) before relying on
// login for seeded users — this placeholder keeps the script runnable
// without a live BCrypt implementation inside mongosh.

db = db.getSiblingDB("splitpay");

db.users.drop();
db.groups.drop();
db.expenses.drop();
db.settlements.drop();
db.payments.drop();

const now = new Date();

// ---- Users (realistic Indian names) ----
const users = [
  { _id: "u_arjun", name: "Arjun Reddy", email: "arjun@example.com" },
  { _id: "u_priya", name: "Priya Sharma", email: "priya@example.com" },
  { _id: "u_karthik", name: "Karthik Iyer", email: "karthik@example.com" },
  { _id: "u_sneha", name: "Sneha Nair", email: "sneha@example.com" },
  { _id: "u_admin", name: "Admin User", email: "admin@splitpay.com", role: "ADMIN" },
];

db.users.insertMany(
  users.map((u) => ({
    _id: u._id,
    name: u.name,
    email: u.email,
    password: bcryptHashOfPassword123,
    role: u.role || "USER",
    createdAt: now,
    updatedAt: now,
  }))
);

// ---- Groups ----
db.groups.insertMany([
  {
    _id: "g_goa",
    name: "Goa Trip",
    description: "Friends weekend trip to Goa",
    createdBy: "u_arjun",
    memberIds: ["u_arjun", "u_priya", "u_karthik", "u_sneha"],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "g_flat",
    name: "Flatmates — HSR Layout",
    description: "Monthly shared flat expenses",
    createdBy: "u_priya",
    memberIds: ["u_priya", "u_karthik"],
    createdAt: now,
    updatedAt: now,
  },
]);

// ---- Expenses (mix of EQUAL / EXACT / PERCENTAGE) ----
db.expenses.insertMany([
  {
    _id: "e_hotel",
    groupId: "g_goa",
    description: "Hotel (3 nights)",
    amount: 12000,
    category: "TRAVEL",
    paidBy: "u_arjun",
    splitType: "EQUAL",
    participants: [
      { userId: "u_arjun", amount: 3000 },
      { userId: "u_priya", amount: 3000 },
      { userId: "u_karthik", amount: 3000 },
      { userId: "u_sneha", amount: 3000 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "e_dinner",
    groupId: "g_goa",
    description: "Beach shack dinner",
    amount: 3000,
    category: "FOOD",
    paidBy: "u_priya",
    splitType: "EXACT",
    participants: [
      { userId: "u_arjun", amount: 1500 },
      { userId: "u_priya", amount: 1000 },
      { userId: "u_karthik", amount: 500 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "e_scooter",
    groupId: "g_goa",
    description: "Scooter rental",
    amount: 2000,
    category: "TRAVEL",
    paidBy: "u_karthik",
    splitType: "PERCENTAGE",
    participants: [
      { userId: "u_arjun", amount: 1000, percentage: 50 },
      { userId: "u_sneha", amount: 1000, percentage: 50 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "e_rent",
    groupId: "g_flat",
    description: "October rent",
    amount: 24000,
    category: "RENT",
    paidBy: "u_priya",
    splitType: "EQUAL",
    participants: [
      { userId: "u_priya", amount: 12000 },
      { userId: "u_karthik", amount: 12000 },
    ],
    createdAt: now,
    updatedAt: now,
  },
]);

// ---- Settlements (one pending, one already completed) ----
db.settlements.insertMany([
  {
    _id: "s_pending_1",
    groupId: "g_goa",
    fromUserId: "u_sneha",
    toUserId: "u_arjun",
    amount: 2000,
    status: "PENDING",
    createdAt: now,
    paidAt: null,
  },
  {
    _id: "s_paid_1",
    groupId: "g_flat",
    fromUserId: "u_karthik",
    toUserId: "u_priya",
    amount: 12000,
    status: "PAID",
    createdAt: now,
    paidAt: now,
  },
]);

db.payments.insertMany([
  {
    _id: "p_paid_1",
    settlementId: "s_paid_1",
    razorpayOrderId: "order_seed_example",
    razorpayPaymentId: "pay_seed_example",
    razorpaySignature: "seed_signature_not_real",
    amount: 12000,
    status: "SUCCESS",
    createdAt: now,
  },
]);

print("SplitPay sample data seeded:");
print("  Users: " + db.users.countDocuments());
print("  Groups: " + db.groups.countDocuments());
print("  Expenses: " + db.expenses.countDocuments());
print("  Settlements: " + db.settlements.countDocuments());
print("  Payments: " + db.payments.countDocuments());
print("");
print("Login with any seeded user's email + 'password123' ONLY after you");
print("replace bcryptHashOfPassword123 at the top of this script with a");
print("real hash (register a throwaway user via /api/auth/register and");
print("copy the resulting `password` field from the users collection).");
